language: csharp

sudo: required
dist: trusty

mono:
  - 4.4.2
  - 4.6.2
  - 4.8.1
  - 5.0.1
  - latest

os:
  - linux
  - osx

matrix:
  # The whole build matrix fails when any individual builds fail (except those which have been allowed with allow_failures).
  fast_finish: true
  allow_failures:
    - mono: latest

env:
  global:
    - MONO_MANAGED_WATCHER=disabled

script:
  - ./build.sh CleanInternetCaches && ./build.sh All

branches:
  except:
    - gh-pages
    - release
