language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.4.2
    - os: osx
      mono: 4.2.0
    - os: osx
      mono: latest
  fast_finish: true


# # Allow builds which fail only on OSX (macOS) to succeed for now
#  # while we're working on getting macOS CI builds working.
#  allow_failures:
#    - os: osx
#  # The whole build matrix fails when any individual builds fail
#  # (except those which have been allowed with allow_failures).

env:
  global:
    - MONO_MANAGED_WATCHER=disabled

script:
  - ./build.sh CleanInternetCaches && ./build.sh All

branches:
  except:
    - gh-pages
    - release
